na:

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -29,23 +29,26 @@ if [ "$1" = 'autoheal' ] && [ -e ${DOCKER_SOCK} ]; then
     while read -r CONTAINER_ID && read -r CONTAINER_NAME && read -r CONTAINER_STATUS; do
         CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
         echo $CONTAINER_STATUS
-        DATE=$(date +%d-%m-%Y" "%H:%M:%S)
-        if [ "null" = "$CONTAINER_NAME" ]; then
-          echo "$DATE Container name of ($CONTAINER_SHORT_ID) is null, which implies container does not exist - don't restart"
-        else
-          echo "Detected $CONTAINER_NAME is restarting"
-          apiUrl="http://localhost/containers/json?filters=\{\"label\":\[\"autohealrestart=true\"\]\}"
-          docker_curl "$apiUrl" | jq -r 'foreach .[] as $CONTAINER([];[]; $CONTAINER | .Id, .Names[0])' | \
-          while read -r CONTAINER_ID && read -r CONTAINER_NAME; do
-             if [ "null" = "$CONTAINER_NAME" ]; then
-              echo "$DATE Container name of ($CONTAINER_SHORT_ID) is null, which implies container does not exist - don't restart"
-            else
-              echo "$DATE Container ${CONTAINER_NAME} ($CONTAINER_SHORT_ID) dependent container is unhealthy - Restarting container now"
-              docker_curl -f -XPOST http://localhost/containers/${CONTAINER_ID}/restart || echo "$DATE Restarting container $CONTAINER_SHORT_ID failed"
-              sleep 10
-              docker_curl -f -XPOST http://localhost/containers/${CONTAINER_ID}/restart || echo "$DATE Restarting container $CONTAINER_SHORT_ID failed"
-            fi
-          done
+        if [ echo $CONTAINER_STATUS | sed 's/.*\(starting\).*/\1/' == "starting"]; then
+          DATE=$(date +%d-%m-%Y" "%H:%M:%S)
+          if [ "null" = "$CONTAINER_NAME" ]; then
+            echo "$DATE Container name of ($CONTAINER_SHORT_ID) is null, which implies container does not exist - don't restart"
+          else
+            echo "Detected $CONTAINER_NAME is restarting"
+            apiUrl="http://localhost/containers/json?filters=\{\"label\":\[\"autohealrestart=true\"\]\}"
+            docker_curl "$apiUrl" | jq -r 'foreach .[] as $CONTAINER([];[]; $CONTAINER | .Id, .Names[0])' | \
+            while read -r CONTAINER_ID && read -r CONTAINER_NAME; do
+              DATE=$(date +%d-%m-%Y" "%H:%M:%S)
+              if [ "null" = "$CONTAINER_NAME" ]; then
+                echo "$DATE Container name of ($CONTAINER_SHORT_ID) is null, which implies container does not exist - don't restart"
+              else
+                echo "$DATE Container ${CONTAINER_NAME} ($CONTAINER_SHORT_ID) dependent container is unhealthy - Restarting container now"
+                docker_curl -f -XPOST http://localhost/containers/${CONTAINER_ID}/restart || echo "$DATE Restarting container $CONTAINER_SHORT_ID failed"
+                sleep 10
+                docker_curl -f -XPOST http://localhost/containers/${CONTAINER_ID}/restart || echo "$DATE Restarting container $CONTAINER_SHORT_ID failed"
+              fi
+            done
+          fi
         fi
     done
   done
